apiVersion: v1
kind: Service
metadata:
  name: capstone-Final
spec:
  type: LoadBalancer
  selector:
    app: capstone-Final
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  selector:
    matchLabels:
      app: capstone-Final
  replicas: 3
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone-pod
        image: mmbayoumi86/capstone-final
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10